

#ifndef __BLE_SECURITY_SERVICE_H__
#define __BLE_SECURITY_SERVICE_H__

typedef enum e_ble_security_service_states{
    BLE_SECURITY_SERVICE_STATE_IDEAL,
    BLE_SECURITY_SERVICE_STATE_READY_PACKET_SENT,
    BLE_SECURITY_SERVICE_STATE_READY_PACKET_ACK_SENT,
    BLE_SECURITY_SERVICE_STATE_CLIENT_PUB_KEY_SENT,
    BLE_SECURITY_SERVICE_STATE_CLIENT_PUB_KEY_STATUS,
    BLE_SECURITY_SERVICE_STATE_SERVER_PUB_KEY_REQ,
    BLE_SECURITY_SERVICE_STATE_SERVER_PUB_KEY_RES,
    BLE_SECURITY_SERVICE_STATE_SESSION_STARTED,
    BLE_SECURITY_SERVICE_STATE_DATA_SENT,
    BLE_SECURITY_SERVICE_STATE_MAX
} e_ble_security_service_states_t;

#endif // __BLE_SECURITY_SERVICE_H__
